### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by gioxx** [AlexHolderDeveloper/CommitsWithinTime#3]
Ciao Alex, using your Action I get the alert regarding a deprecated version of Node.js (12), would you be so kind to update Node.js 16?
`Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: AlexHolderDeveloper/CommitsWithinTime@v1.1.10. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`

Thanks a lot for your work! 😄

**Comment by AlexHolderDeveloper** [comment]
Hey, thankyou for noticing this! I've just made some quick edits in the Github web editor so in theory the new version should work, but please let me know if there's issues and I'll do a proper fix-up :)

**Comment by gioxx** [comment]
Oh! Thanks @AlexHolderDeveloper!
I would like to take this opportunity to also add another type of output that is also generated by your Action and should also be updated (see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/):

`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

In the meantime I'll going to make a test with the new version 👍

**Comment by gioxx** [comment]
I just ran a test and everything works like a charm, even the additional warning I had given you above is completely gone!
Again thank you very much for your help in such a short time, have a good weekend! 👊 🤗
